query GetPosts($input: PostFilterInput!, $getPostsPage2: PaginationInput) {
  getPosts(input: $input, page: $getPostsPage2) {
    id
    title
    body
    commentCount
    attachments {
      id
      cid
      title
      type
      url
    }
    base {
      id
      createdAt
      visibility
      user {
        id
        address
        displayName
        email
        verified
        profile {
          bio
          cover
          picture
          username
        }
        socials {
          platform
          url
        }
      }
    }
  }
}
