query GetPosts($query: String!, $limit: Int) {
  getPosts(query: $query, limit: $limit) {
    author {
      address
      bio
      displayName
      username
      profilePicture
      coverPicture
    }
    bookmarkCount
    cid
    commentCount
    createdAt
    description
    id
    likeCount
    media {
      url
      type
      title
      id
      cid
    }
    title
    updatedAt
    viewCount
    visibility
  }
}
