name: Bug Fix
description: Issues related to bug fixes
title: 'fix: '
type: bug
labels:
  - bug
assignees:
  - cswni
  - jadapema
projects:
  - WatchItDev/9
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Include the details of the bug fix
    validations:
      required: true
  - type: input
    id: filename
    attributes:
      label: Filename / Path
      description: Add the file or path where the bug is located
    validations:
      required: false
