name: Create a test
description: Testing for ensuring the quality of the code
title: "test: "
type: test
labels:
  - test
assignees:
  - cswni
  - jadapema
projects:
  - WatchItDev/9
body:
  - type: input
    id: feature-title
    attributes:
      label: Test title
      description: Describe the test scope
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Include the purpose of the test
    validations:
      required: true
  - type: input
    id: filename
    attributes:
      label: Filename / Path
      description: Add the file or path where the test is located
    validations:
      required: true
