query GetCommentsByPost($postId: Int!, $limit: Int, $offset: Int) {
  getComments(input: { postId: $postId }, page: { limit: $limit, offset: $offset }) {
    id
    body
    post {
      id
    }
    parent {
      id
    }
    base {
      id
      createdAt
      user {
        id
        address
        displayName
        verified
        profile {
          username
          picture
          cover
          bio
        }
        socials {
          platform
          url
        }
      }
    }
  }
}
