import {
  GetAllPostsDocument,
  GetPopularPostsDocument,
  GetRecentUsersDocument,
  GetRecentPostsDocument,
} from "@src/graphql/generated/graphql";

export const exploreViewMock = [
  {
    request: {
      query: GetAllPostsDocument,
    },
    result: {
      data: {
        getAllPosts: [
          {
            id: "1",
            title: "Título de prueba",
            description: "Descripción",
            visibility: "PUBLIC",
            commentCount: 0,
            likeCount: 0,
            bookmarkCount: 0,
            viewCount: 0,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            cid: "somecid",
            author: {
              address: "0x123",
              displayName: "Autor Prueba",
              followersCount: 10,
              followingCount: 5,
              coverPicture: "cover.jpg",
              profilePicture: "profile.jpg",
              bio: "Bio",
              publicationsCount: 2,
              username: "autorprueba",
              __typename: "User",
            },
            media: [],
            __typename: "Post",
          },
        ],
      },
    },
  },
  {
    request: {
      query: GetPopularPostsDocument,
      variables: {
        limit: 10,
      },
    },
    result: {
      data: {
        getPopularPosts: [
          {
            id: "2",
            title: "Popular Post",
            description: "Popular Description",
            visibility: "PUBLIC",
            commentCount: 1,
            likeCount: 2,
            bookmarkCount: 3,
            viewCount: 4,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            cid: "popularcid",
            author: {
              address: "0x456",
              displayName: "Popular Author",
              followersCount: 20,
              followingCount: 10,
              coverPicture: "cover2.jpg",
              profilePicture: "profile2.jpg",
              bio: "Popular Bio",
              publicationsCount: 5,
              username: "popularauthor",
              __typename: "User",
            },
            media: [],
            __typename: "Post",
          },
          {
            id: "2",
            title: "Popular Post",
            description: "Popular Description",
            visibility: "PUBLIC",
            commentCount: 1,
            likeCount: 2,
            bookmarkCount: 3,
            viewCount: 4,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            cid: "popularcid",
            author: {
              address: "0x456",
              displayName: "Popular Author",
              followersCount: 20,
              followingCount: 10,
              coverPicture: "cover2.jpg",
              profilePicture: "profile2.jpg",
              bio: "Popular Bio",
              publicationsCount: 5,
              username: "popularauthor",
              __typename: "User",
            },
            media: [],
            __typename: "Post",
          },
        ],
      },
    },
  },
  {
    request: {
      query: GetRecentUsersDocument,
      variables: {
        limit: 50,
      },
    },
    result: {
      data: {
        getRecentUsers: [
          {
            address: "0x000000000000000000000000000000000000dead",
            bio: "Recent User Bio",
            bookmarksCount: 1,
            coverPicture: "cover3.jpg",
            createdAt: new Date().toISOString(),
            displayName: "Recent User",
            followersCount: 5,
            followingCount: 2,
            profilePicture: "profile3.jpg",
            publicationsCount: 1,
            socialLinks: [],
            updatedAt: new Date().toISOString(),
            username: "recentuser",
            verified: false,
            xpBalance: 100,
            __typename: "User",
          },
        ],
      },
    },
  },
  {
    request: {
      query: GetRecentPostsDocument,
      variables: { limit: 100 },
    },
    result: {
      data: {
        getRecentPosts: [
          {
            id: "3",
            title: "Post con límite 100",
            description: "Descripción",
            visibility: "PUBLIC",
            commentCount: 0,
            likeCount: 0,
            bookmarkCount: 0,
            viewCount: 0,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            cid: "cid100",
            author: {
              address: "0xabc",
              displayName: "Autor 100",
              followersCount: 15,
              followingCount: 3,
              coverPicture: "cover.jpg",
              profilePicture: "profile.jpg",
              bio: "Bio",
              publicationsCount: 2,
              username: "autor100",
              __typename: "User",
            },
            media: [],
            __typename: "Post",
          },
        ],
      },
    },
  },
  {
    request: {
      query: GetRecentPostsDocument,
      variables: { limit: 20 },
    },
    result: {
      data: {
        getRecentPosts: [
          {
            id: "4",
            title: "Post con límite 20",
            description: "Otra descripción",
            visibility: "PUBLIC",
            commentCount: 1,
            likeCount: 1,
            bookmarkCount: 1,
            viewCount: 1,
            updatedAt: new Date().toISOString(),
            createdAt: new Date().toISOString(),
            cid: "cid20",
            author: {
              address: "0xdef",
              displayName: "Autor 20",
              followersCount: 10,
              followingCount: 4,
              coverPicture: "cover2.jpg",
              profilePicture: "profile2.jpg",
              bio: "Bio del autor",
              publicationsCount: 1,
              username: "autor20",
              __typename: "User",
            },
            media: [],
            __typename: "Post",
          },
        ],
      },
    },
  },
];
