query GetUser($input: UserByInput!) {
  getUser(input: $input) {
    address
    username
    displayName
    bio
    profilePicture
    coverPicture
    currentRank
    xpTotal
    xpBalance
    followersCount
    followingCount
    publicationsCount
    bookmarksCount
    socialLinks {
      platform
      url
    }
    verified
    createdAt
    updatedAt
  }
}
