query GetUserBookmarks($address: String!, $limit: Int) {
  getUserBookmarks(address: $address, limit: $limit) {
    id
    title
    description
    media {
      url
      cid
      title
      type
    }
    createdAt
  }
}
