name: CD

on:
  workflow_call:
    inputs:
      environment:
        description: "Deploy environment"
        default: "next"
        required: false
        type: string

concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  app:
    # if we add in the commit [no android] android build is ignored
    if: ${{ !contains(github.event.head_commit.message, '[no android]') }}
    environment: ${{ inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'tem'

      - name: Install dependencies
        run: npm ci

      - name: Collecting .env from dotenv-vault
        run: npx dotenv-vault@latest pull -m ${{ secrets.DOTENV_ME }} -y

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          working-directory: "android"

      - name: Deploying Android
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "beta"
          subdirectory: "android"

  