name: CD
on:
  push:
    branches:
      - "master"
      - "v1.0.0"

concurrency:
  group: ${{ inputs.os }}
  cancel-in-progress: true

jobs:
  build-app:
    # if we add in the commit [no android] android build is ignored
    strategy:
     matrix:
       # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
       include:
        - os: ubuntu-latest
          command: packagelinux
        - os: macos-latest
          command: packagemac
        - os: windows-latest
          command: packagewin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js in linux
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: npm ci

      - name: Build/release
        run: make ${{ matrix.command }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

