name: CI

on:
  workflow_call:
  # https://github.com/marketplace/actions/jest-coverage-report#forks-with-no-write-permission
  pull_request:

jobs:
  ci:
    name: Static Analysis and Test | Node ${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run static analysis
        run: npm run lint

      - name: Test with coverage
        run: npm run test -- --coverage --silent

      #- name: Generate report
      #  run: make testcov
