name: CI

on:
  workflow_call:
  # https://github.com/marketplace/actions/jest-coverage-report#forks-with-no-write-permission
  pull_request:

jobs:
  ci:
    name: Static Analysis and Test | Node ${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run static analysis
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Generate coverage report
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: WatchItDev/watchit-app
